# Lokad_Purchase Orders

The file describes about the historical purchase data for every transactional shipment.
ID: the SKU (Stock keeping Unit) identifier (value: 10014552/Chicago)
Loc: the identifier of the geographical location (value: Chicago)
Ref: the identifier of the product (value: 10014552)
DeliveryDate: date when the good were delivered, missing values for some which I guess represent the order for which goods are not delivered (value: 22-06-16)
Quantity: order quantity in units (value: 50)
Received: received quantity in units (value: 50)
NetAmount: amount paid for the purchase order (value: 165)
Supplier: identifies the supplier who received the purchase order (value: FHL)
PoNumber: unique identifier for purchase order (value: PONumber)
Date: date when the purchase order was placed (value: 20-04-16)
Currency: code for the currency (value: USD)

In [1]:
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

## Reading csv file

In [2]:
df = pd.read_csv("Lokad_PurchaseOrders.csv", index_col = 0)
df

,Loc,Ref,DeliveryDate,Quantity,Received,NetAmount,Supplier,PONumber,Date,Currency
Id,,,,,,,,,,
15641711/Los Angeles,Los Angeles,15641711,6/22/2016,50,50,164.999998,FHL,PO-200193,4/20/2016,USD
15641711/Los Angeles,Los Angeles,15641711,7/29/2016,47,47,155.099998,FHL,PO-200243,7/26/2016,USD
16075571/Los Angeles,Los Angeles,16075571,6/22/2016,100,100,300.000000,Logipro,PO-200193,4/20/2016,GBP
16075571/Los Angeles,Los Angeles,16075571,7/29/2016,300,300,900.000000,Logipro,PO-200243,7/26/2016,GBP
16075571/Los Angeles,Los Angeles,16075571,1/1/2001,121,0,363.000000,Logipro,PO-200271,8/24/2016,GBP
14759689/Los Angeles,Los Angeles,14759689,1/1/2001,103,0,336.809998,Drecom,PO-200271,8/24/2016,GBP
14095459/Los Angeles,Los Angeles,14095459,1/1/2001,100,0,4654.999920,Drecom,PO-200225,8/6/2016,USD
15586718/Los Angeles,Los Angeles,15586718,1/1/2001,200,0,11400.000000,Drecom,PO-200225,8/6/2016,GBP
10095232/Los Angeles,Los Angeles,10095232,5/8/2015,150,150,4002.000045,Office First,102196,5/27/2015,EUR
10095232/Los Angeles,Los Angeles,10095232,6/21/2016,100,100,2668.000030,Office First,PO-200069,11/25/2015,EUR
10095232/Los Angeles,Los Angeles,10095232,6/20/2016,100,100,2668.000030,Office First,PO-200081,10/12/2015,EUR
11481389/Los Angeles,Los Angeles,11481389,1/1/2001,2,0,26.480000,SuperSupply,PO-200257,4/8/2016,GBP
15431986/Los Angeles,Los Angeles,15431986,6/21/2016,24,24,291.120002,Logipro,PO-200069,11/25/2015,GBP
15431986/Los Angeles,Los Angeles,15431986,1/1/2001,6,0,72.780001,Logipro,PO-200271,8/24/2016,GBP
12768029/Los Angeles,Los Angeles,12768029,6/14/2016,12,12,218.400010,FHL,PO-200099,7/1/2016,USD
12768029/Los Angeles,Los Angeles,12768029,1/1/2001,2,0,36.400002,FHL,PO-200257,4/8/2016,USD
15343952/Los Angeles,Los Angeles,15343952,1/1/2001,120,0,2743.200072,Logipro,PO-EE-BO-Atlanta,10/30/2015,GBP
15343952/Los Angeles,Los Angeles,15343952,4/10/2016,40,0,914.400024,Logipro,PO-200244,7/26/2016,GBP
14693335/Los Angeles,Los Angeles,14693335,4/10/2016,32,0,1126.719971,Drecom,PO-200244,7/26/2016,USD
11711636/Los Angeles,Los Angeles,11711636,1/1/2001,40,0,996.399992,RRD,PO-EE-BO-Atlanta,10/30/2015,USD
11711636/Los Angeles,Los Angeles,11711636,6/21/2016,16,16,398.559997,RRD,PO-200069,11/25/2015,USD
11711636/Los Angeles,Los Angeles,11711636,1/1/2001,20,0,498.199996,RRD,PO-200267,8/18/2016,USD
11941800/Los Angeles,Los Angeles,11941800,1/1/2001,40,0,996.399992,Drecom,PO-EE-BO-Atlanta,10/30/2015,GBP
11941800/Los Angeles,Los Angeles,11941800,6/21/2016,16,16,398.559997,Drecom,PO-200069,11/25/2015,GBP
11941800/Los Angeles,Los Angeles,11941800,1/1/2001,20,0,498.199996,Drecom,PO-200267,8/18/2016,GBP
11711100/Los Angeles,Los Angeles,11711100,1/1/2001,24,0,335.280007,Office First,PO-200277,8/31/2016,USD
10595489/Los Angeles,Los Angeles,10595489,5/8/2015,18,18,681.120004,SuperSupply,102196,5/27/2015,EUR
10595489/Los Angeles,Los Angeles,10595489,6/21/2016,12,12,454.080002,SuperSupply,PO-200069,11/25/2015,EUR
10595489/Los Angeles,Los Angeles,10595489,12/9/2016,20,0,756.800004,SuperSupply,PO-200236,7/13/2016,EUR
10678449/Los Angeles,Los Angeles,10678449,4/10/2016,20,0,661.200028,SuperSupply,PO-200244,7/26/2016,USD
...,...,...,...,...,...,...,...,...,...,...
13985896/Chicago,Chicago,13985896,7/26/2016,12,12,546.720017,Drecom,PO-200200,3/5/2016,GBP
13985896/Chicago,Chicago,13985896,1/1/2001,12,0,546.720017,Drecom,PO-200290,9/28/2016,GBP
16363786/Chicago,Chicago,16363786,5/2/2016,10,10,233.999996,Drecom,PO-200091,12/22/2015,USD
15963625/Chicago,Chicago,15963625,5/2/2016,20,20,589.000016,RRD,PO-200091,12/22/2015,USD
15963625/Chicago,Chicago,15963625,1/1/2001,10,0,294.500008,RRD,PO-200281,9/15/2016,USD
16018733/Chicago,Chicago,16018733,12/31/2015,10,10,203.600006,RRD,PO-200052,12/11/2015,USD
16018733/Chicago,Chicago,16018733,5/19/2016,40,40,814.400024,RRD,PO-200176,3/30/2016,USD
14099484/Chicago,Chicago,14099484,12/31/2015,10,10,317.399998,Drecom,PO-200052,12/11/2015,GBP
14099484/Chicago,Chicago,14099484,1/28/2016,20,20,634.799996,Drecom,PO-200085,12/17/2015,GBP
14099484/Chicago,Chicago,14099484,4/5/2016,50,50,1586.999990,Drecom,PO-200141,2/16/2016,GBP
16277400/Chicago,Chicago,16277400,4/13/2016,16,16,360.640014,SuperSupply,PO-200133,11/2/2016,USD
16277400/Chicago,Chicago,16277400,7/26/2016,20,20,450.800018,SuperSupply,PO-200200,3/5/2016,USD
16277400/Chicago,Chicago,16277400,3/8/2016,10,10,225.400009,SuperSupply,PO-200206,5/13/2016,USD
12451991/Chicago,Chicago,12451991,4/13/2016,16,16,360.640014,RRD,PO-200133,11/2/2016,GBP
12451991/Chicago,Chicago,12451991,7/26/2016,20,20,450.800018,RRD,PO-200200,3/5/2016,GBP
12451991/Chicago,Chicago,12451991,3/8/2016,10,10,225.400009,RRD,PO-200206,5/13/2016,GBP
13060917/Chicago,Chicago,13060917,1/1/2001,20,0,698.399964,RRD,PO-EE-BO-Reno,10/30/2015,EUR
13060917/Chicago,Chicago,13060917,8/1/2016,10,10,349.199982,RRD,PO-200062,11/19/2015,EUR
13060917/Chicago,Chicago,13060917,5/2/2016,10,10,349.199982,RRD,PO-200091,12/22/2015,EUR
13060917/Chicago,Chicago,13060917,7/6/2016,20,20,698.399964,RRD,PO-200189,4/13/2016,EUR
14404386/Chicago,Chicago,14404386,1/18/2016,10,10,633.100014,Drecom,PO-200074,3/12/2015,GBP
14404386/Chicago,Chicago,14404386,6/5/2016,10,10,633.100014,Drecom,PO-200160,3/15/2016,GBP
14404386/Chicago,Chicago,14404386,6/20/2016,20,20,1266.200028,Drecom,PO-200192,4/19/2016,GBP
14404386/Chicago,Chicago,14404386,1/1/2001,16,0,1012.960022,Drecom,PO-200298,10/20/2016,GBP
14411646/Chicago,Chicago,14411646,12/22/2015,16,16,295.519989,Drecom,PO-200044,10/30/2015,USD
14411646/Chicago,Chicago,14411646,5/2/2016,8,8,147.759994,Drecom,PO-200091,12/22/2015,USD
14411646/Chicago,Chicago,14411646,6/20/2016,16,16,295.519989,Drecom,PO-200192,4/19/2016,USD
16188573/Chicago,Chicago,16188573,12/22/2015,16,16,295.519989,FHL,PO-200044,10/30/2015,GBP
16188573/Chicago,Chicago,16188573,5/2/2016,8,8,147.759994,FHL,PO-200091,12/22/2015,GBP
16188573/Chicago,Chicago,16188573,6/20/2016,16,16,295.519989,FHL,PO-200192,4/19/2016,GBP

In [3]:
df.dtypes

Loc              object
Ref               int64
DeliveryDate     object
Quantity          int64
Received          int64
NetAmount       float64
Supplier         object
PONumber         object
Date             object
Currency         object
dtype: object

#### Conversion of the dtypes of Date and Delivery date coulmns of Lokad_PurchaseOrders into datetime

In [4]:
df['Date']  = pd.to_datetime(df['Date'])
df['DeliveryDate'] = pd.to_datetime(df['DeliveryDate'])
#df.dtypes

#### Lead time calculation

#### Lead_Time = SupplyDelay + Constant(Reorder delay)
#### Reorder delay is kept constant as it depends on the business agreement with the supplier. For our case right now taken reorder as zero

In [5]:
df['LeadTime'] = abs(df.DeliveryDate - df.Date)

In [6]:
df['LeadTime']

Id
15641711/Los Angeles     63 days
15641711/Los Angeles      3 days
16075571/Los Angeles     63 days
16075571/Los Angeles      3 days
16075571/Los Angeles   5714 days
14759689/Los Angeles   5714 days
14095459/Los Angeles   5696 days
15586718/Los Angeles   5696 days
10095232/Los Angeles     19 days
10095232/Los Angeles    209 days
10095232/Los Angeles    252 days
11481389/Los Angeles   5576 days
15431986/Los Angeles    209 days
15431986/Los Angeles   5714 days
12768029/Los Angeles     17 days
12768029/Los Angeles   5576 days
15343952/Los Angeles   5415 days
15343952/Los Angeles    107 days
14693335/Los Angeles    107 days
11711636/Los Angeles   5415 days
11711636/Los Angeles    209 days
11711636/Los Angeles   5708 days
11941800/Los Angeles   5415 days
11941800/Los Angeles    209 days
11941800/Los Angeles   5708 days
11711100/Los Angeles   5721 days
10595489/Los Angeles     19 days
10595489/Los Angeles    209 days
10595489/Los Angeles    149 days
10678449/Los Angeles    107 days
                          ...
13985896/Chicago        143 days
13985896/Chicago       5749 days
16363786/Chicago        132 days
15963625/Chicago        132 days
15963625/Chicago       5736 days
16018733/Chicago         20 days
16018733/Chicago         50 days
14099484/Chicago         20 days
14099484/Chicago         42 days
14099484/Chicago         49 days
16277400/Chicago        203 days
16277400/Chicago        143 days
16277400/Chicago         66 days
12451991/Chicago        203 days
12451991/Chicago        143 days
12451991/Chicago         66 days
13060917/Chicago       5415 days
13060917/Chicago        256 days
13060917/Chicago        132 days
13060917/Chicago         84 days
14404386/Chicago        312 days
14404386/Chicago         82 days
14404386/Chicago         62 days
14404386/Chicago       5771 days
14411646/Chicago         53 days
14411646/Chicago        132 days
14411646/Chicago         62 days
16188573/Chicago         53 days
16188573/Chicago        132 days
16188573/Chicago         62 days
Name: LeadTime, Length: 1076, dtype: timedelta64[ns]

In [7]:
df.dtypes

Loc                      object
Ref                       int64
DeliveryDate     datetime64[ns]
Quantity                  int64
Received                  int64
NetAmount               float64
Supplier                 object
PONumber                 object
Date             datetime64[ns]
Currency                 object
LeadTime        timedelta64[ns]
dtype: object

#### Conversion of dtypes of Leadtime to int

In [8]:
df['LeadTime']  = (df['LeadTime'] / np.timedelta64(1, 'D')).astype(int)

In [9]:
df.dtypes

Loc                     object
Ref                      int64
DeliveryDate    datetime64[ns]
Quantity                 int64
Received                 int64
NetAmount              float64
Supplier                object
PONumber                object
Date            datetime64[ns]
Currency                object
LeadTime                 int32
dtype: object

In [10]:
df['LeadTime'].to_csv('temp.csv')

In [11]:
colname = ['LeadTime']
df2 = pd.read_csv('temp.csv', names = colname, header = None)
df.merge(df2, right_index = False, left_index = False).to_csv('temp1.csv')

### Calculation of Average Lead Time

In [12]:
avg_supp = df.groupby('Ref', as_index = True)['LeadTime'].mean().astype(int)

colnames=['Ref', 'AvgLT'] 
avg_supp.to_csv('temp.csv')

data = pd.read_csv('temp.csv', names = colnames, header = None)

data

         Ref  AvgLT
0    9952426     58
1   10014552   1421
2   10095232    144
3   10099950   2213
4   10132892    669
5   10136626    885
6   10210677   1049
7   10255812    886
8   10422793     85
9   10592438    783
10  10595489    670
11  10678449   1988
12  10764226     69
13  11045096   2335
14  11097836    946
15  11481389   1200
16  11557472    150
17  11635178     58
18  11711100   1981
19  11711636   1133
20  11780124   2444
21  11788268   1049
22  11800905     92
23  11906239   1049
24  11914966    629
25  11929369   2115
26  11941800   1133
27  12401265    160
28  12409642   1968
29  12451991   1159
..       ...    ...
70  14789055    979
71  14820865     92
72  14895172    114
73  14901389     32
74  15034737   1325
75  15063964    895
76  15092233    992
77  15149291    869
78  15343952   1915
79  15410849   1746
80  15416092   2103
81  15431986   1657
82  15519926   1493
83  15586718   2904
84  15641711   2277
85  15808622    702
86  15880950   1402
87  15963625   2448
88  16018733   1197
89  16075571    886
90  16089695    783
91  16187687   2163
92  16188573   1224
93  16239251   1543
94  16277400   1159
95  16363786   1452
96  16401974    933
97  16412231   1217
98  16430058   1002
99  16595101   1021

[100 rows x 2 columns]

In [13]:
new_df = df.merge(data, on = 'Ref', right_index = True).to_csv('temp1.csv')

new_df = pd.read_csv('temp1.csv')

### LeadTime deviation

In [14]:
sigma_LT = new_df.groupby('Ref')['LeadTime'].std().fillna(0).astype(int)
sigma_LT.to_csv('temp.csv')
colname = ['Ref', 'sigmaLT']
df3 = pd.read_csv('temp.csv', names = colname, header = None)
df3

         Ref  sigmaLT
0    9952426       36
1   10014552     2454
2   10095232      165
3   10099950     2851
4   10132892     1793
5   10136626     2153
6   10210677     2279
7   10255812     2129
8   10422793      103
9   10592438     1940
10  10595489     1681
11  10678449     2750
12  10764226       71
13  11045096     2924
14  11097836     2000
15  11481389     2448
16  11557472      119
17  11635178        0
18  11711100     2803
19  11711636     2208
20  11780124     2885
21  11788268     2279
22  11800905       72
23  11906239     2160
24  11914966     1638
25  11929369     3116
26  11941800     2208
27  12401265      224
28  12409642     2740
29  12451991     2272
..       ...      ...
70  14789055     2064
71  14820865       68
72  14895172       93
73  14901389       41
74  15034737     2460
75  15063964     1977
76  15092233     2074
77  15149291     1989
78  15343952     2755
79  15410849     2607
80  15416092     2858
81  15431986     2591
82  15519926     2422
83  15586718     3005
84  15641711     2947
85  15808622     1831
86  15880950     2389
87  15963625     3001
88  16018733     2292
89  16075571     2129
90  16089695     1940
91  16187687     2712
92  16188573     2385
93  16239251     2613
94  16277400     2272
95  16363786     2497
96  16401974     2040
97  16412231     2336
98  16430058     2308
99  16595101     2169

[100 rows x 2 columns]

In [15]:
new_df.merge(df3, on = 'Ref', right_index = True).to_csv('temp1.csv')
new_df

,Id,Loc,Ref,DeliveryDate,Quantity,Received,NetAmount,Supplier,PONumber,Date,Currency,LeadTime,AvgLT
0,15641711/Los Angeles,Los Angeles,15641711,2016-06-22,50,50,164.999998,FHL,PO-200193,2016-04-20,USD,63,2277
1,15641711/Los Angeles,Los Angeles,15641711,2016-07-29,47,47,155.099998,FHL,PO-200243,2016-07-26,USD,3,2277
2,15641711/New-York,New-York,15641711,2016-12-04,800,800,2639.999960,FHL,PO-200121,2016-01-25,USD,314,2277
3,15641711/New-York,New-York,15641711,2001-01-01,100,0,329.999995,FHL,PO-200123,2016-01-26,USD,5503,2277
4,15641711/Chicago,Chicago,15641711,2001-01-01,100,0,329.999995,FHL,PO-200122,2016-01-26,USD,5503,2277
5,16075571/Los Angeles,Los Angeles,16075571,2016-06-22,100,100,300.000000,Logipro,PO-200193,2016-04-20,GBP,63,886
6,16075571/Los Angeles,Los Angeles,16075571,2016-07-29,300,300,900.000000,Logipro,PO-200243,2016-07-26,GBP,3,886
7,16075571/Los Angeles,Los Angeles,16075571,2001-01-01,121,0,363.000000,Logipro,PO-200271,2016-08-24,GBP,5714,886
8,16075571/New-York,New-York,16075571,2016-06-22,200,200,600.000000,Logipro,PO-200131,2016-09-02,GBP,72,886
9,16075571/New-York,New-York,16075571,2016-01-08,2400,2300,7200.000000,Logipro,PO-200240,2016-07-19,GBP,193,886
10,16075571/New-York,New-York,16075571,2016-05-08,2100,2100,6300.000000,Logipro,PO-200246,2016-07-28,GBP,81,886
11,16075571/Chicago,Chicago,16075571,2016-03-22,100,100,300.000000,Logipro,PO-200148,2016-01-03,GBP,79,886
12,14759689/Los Angeles,Los Angeles,14759689,2001-01-01,103,0,336.809998,Drecom,PO-200271,2016-08-24,GBP,5714,2047
13,14759689/New-York,New-York,14759689,2016-08-02,4000,4000,13079.999920,Drecom,PO-200101,2016-12-01,GBP,121,2047
14,14759689/Chicago,Chicago,14759689,2016-01-29,1000,1000,3269.999980,Drecom,PO-200103,2016-12-01,GBP,307,2047
15,14095459/Los Angeles,Los Angeles,14095459,2001-01-01,100,0,4654.999920,Drecom,PO-200225,2016-08-06,USD,5696,996
16,14095459/New-York,New-York,14095459,2015-10-28,3,3,139.649998,Drecom,PO-200031,2015-10-13,USD,15,996
17,14095459/New-York,New-York,14095459,2016-01-18,200,200,9309.999840,Drecom,PO-200088,2015-12-17,USD,32,996
18,14095459/New-York,New-York,14095459,2016-08-29,100,100,4654.999920,Drecom,PO-200178,2016-04-04,USD,147,996
19,14095459/Chicago,Chicago,14095459,2016-04-05,50,50,2327.499960,Drecom,PO-200147,2016-02-26,USD,39,996
20,14095459/Chicago,Chicago,14095459,2016-05-08,50,50,2327.499960,Drecom,PO-200165,2016-03-18,USD,51,996
21,15586718/Los Angeles,Los Angeles,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200225,2016-08-06,GBP,5696,2904
22,15586718/New-York,New-York,15586718,2016-01-18,14,14,798.000000,Drecom,PO-200088,2015-12-17,GBP,32,2904
23,15586718/New-York,New-York,15586718,2016-01-04,110,110,6270.000000,Drecom,PO-200118,2016-01-21,GBP,17,2904
24,15586718/New-York,New-York,15586718,2016-07-25,200,200,11400.000000,Drecom,PO-200164,2016-03-18,GBP,129,2904
25,15586718/New-York,New-York,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200284,2016-09-20,GBP,5741,2904
26,15586718/New-York,New-York,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200301,2016-10-26,GBP,5777,2904
27,15586718/Chicago,Chicago,15586718,2016-04-05,55,55,3135.000000,Drecom,PO-200147,2016-02-26,GBP,39,2904
28,15586718/Chicago,Chicago,15586718,2016-05-08,99,99,5643.000000,Drecom,PO-200165,2016-03-18,GBP,51,2904
29,15586718/Chicago,Chicago,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200285,2016-09-20,GBP,5741,2904
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,10132892/Chicago,Chicago,10132892,2016-06-20,12,12,556.560013,Drecom,PO-200192,2016-04-19,USD,62,669
1047,14339722/New-York,New-York,14339722,2015-05-10,40,40,1762.799988,Drecom,PO-200009,2015-03-08,USD,63,80
1048,14339722/New-York,New-York,14339722,2015-10-26,40,40,1762.799988,Drecom,PO-200017,2015-08-31,USD,56,80
1049,14339722/New-York,New-York,14339722,2015-10-29,20,20,881.399994,Drecom,PO-200023,2015-09-15,USD,44,80
1050,14339722/New-York,New-York,14339722,2016-06-01,20,20,881.399994,Drecom,PO-200038,2015-10-29,USD,216,80
1051,14339722/New-York,New-York,14339722,2016-02-15,28,28,1233.959992,Drecom,PO-200090,2015-12-21,USD,56,80
1052,14339722/New-York,New-York,14339722,2016-06-17,26,26,1145.819992,Drecom,PO-200191,2016-04-19,USD,59,80
1053,14339722/New-York,New-York,14339722,2016-06-21,14,14,616.979996,Drecom,PO-200196,2016-04-25,USD,57,80
1054,14339722/New-York,New-York,14339722,2016-06-23,20,20,881.399994,Drecom,PO-200198,2016-04-26,USD,58,80
1055,14339722/New-York,New-York,14339722,2016-01-08,20,20,881.399994,Drecom,PO-200215,2016-02-06,USD,29,80
1056,14339722/Chicago,Chicago,14339722,2015-12-22,12,12,528.839996,Drecom,PO-200044,2015-10-30,USD,53,80
1057,14339722/Chicago,Chicago,14339722,2016-05-02,10,10,440.699997,Drecom,PO-200091,2015-12-22,USD,132,80
1058,14339722/Chicago,Chicago,14339722,2016-07-26,40,40,1762.799988,Drecom,PO-200200,2016-03-05,USD,143,80
1059,15963625/New-York,New-York,15963625,2015-10-26,30,30,883.500024,RRD,PO-200018,2015-01-09,USD,290,2448
1060,15963625/New-York,New-York,15963625,2016-12-02,50,50,1472.500040,RRD,PO-200087,2015-12-17,USD,351,2448
1061,15963625/New-York,New-York,15963625,2001-01-01,20,0,589.000016,RRD,PO-200280,2016-09-14,USD,5735,2448
1062,15963625/Chicago,Chicago,15963625,2016-05-02,20,20,589.000016,RRD,PO-200091,2015-12-22,USD,132,2448
1063,15963625/Chicago,Chicago,15963625,2001-01-01,10,0,294.500008,RRD,PO-200281,2016-09-15,USD,5736,2448
1064,14404386/New-York,New-York,14404386,2015-11-11,20,20,1266.200028,Drecom,PO-200024,2015-09-22,GBP,50,1500
1065,14404386/New-York,New-York,14404386,2015-12-31,36,36,2279.160050,Drecom,PO-200034,2015-10-22,GBP,70,1500
1066,14404386/New-York,New-York,14404386,2016-01-18,16,16,1012.960022,Drecom,PO-200059,2015-11-18,GBP,61,1500
1067,14404386/New-York,New-York,14404386,2016-02-18,12,12,759.720017,Drecom,PO-200083,2015-12-15,GBP,65,1500
1068,14404386/New-York,New-York,14404386,2016-06-21,30,30,1899.300042,Drecom,PO-200196,2016-04-25,GBP,57,1500
1069,14404386/New-York,New-York,14404386,2016-07-26,20,20,1266.200028,Drecom,PO-200204,2016-12-05,GBP,132,1500
1070,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200293,2016-04-10,GBP,5578,1500
1071,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200297,2016-10-19,GBP,5770,1500
1072,14404386/Chicago,Chicago,14404386,2016-01-18,10,10,633.100014,Drecom,PO-200074,2015-03-12,GBP,312,1500
1073,14404386/Chicago,Chicago,14404386,2016-06-05,10,10,633.100014,Drecom,PO-200160,2016-03-15,GBP,82,1500
1074,14404386/Chicago,Chicago,14404386,2016-06-20,20,20,1266.200028,Drecom,PO-200192,2016-04-19,GBP,62,1500
1075,14404386/Chicago,Chicago,14404386,2001-01-01,16,0,1012.960022,Drecom,PO-200298,2016-10-20,GBP,5771,1500

### Forecating of the Leadtime from the given input using different Machine Learning algorithm

#### DecisionTreeForecasting

In [16]:
## Forecasting the Leadtime for the product

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X = df[['Date', 'DeliveryDate']]

y = new_df['AvgLT']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

dt = DecisionTreeClassifier().fit(X_train, y_train)
# dt.score(X_train,y_train) * 100

In [17]:
pred = dt.predict(X_test)
print("Accuracy Score: ", accuracy_score(pred, y_test) * 100)

Accuracy Score:  6.69144981413

#### Feature importance

In [18]:
# Feature imporatnce using DecisionTreelassifier
print(dt.feature_importances_)

[ 0.63015074  0.36984926]

#### Forecasting using ExtraTreeClassifier

In [22]:
#from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
# load the iris datasets
X = df[['Date', 'DeliveryDate']]

y = new_df['AvgLT']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
# fit an Extra Trees model to the data
model = ExtraTreesClassifier()
model.fit(X, y)
# display the relative importance of each attribute
print(model.feature_importances_)

[ 0.58744905  0.41255095]

In [23]:
model.score(X_test, y_test)

0.17843866171003717