## Lokad_Orders

This file contains the historical sales data
ID: the SKU (Stock keeping Unit) identifier (value: 10014552/Chicago)
Loc: the identifier of the geographical location (value: Chicago)
Ref: the identifier of the product (value: 10014552)
Date: ordering date (value: 4/4/2013 for some cases the values are missing)
Quantity: quantity ordered in units (value: 1)
NetAmount: amount paid for order (value: 135.8)
OrderId: unique identifier for the customer order (value: 1.98E+08)
Currency: code for the currency(value : USD)
Client: a client indentifier (value: 17538)

Lead Demand: The projected level of demand for a product from consumers during its lead time from the supplier to the retailer

For our calaculation, 

Lead Demand(LD) = LeadTime(LT in days) * Avg Daily usage(of product in days)

In our case Leasd Time is sam as AvgSupplyDelay as the reorder delay in our case is zer for the time being.

In [1]:
% matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#pd.get_option("display.max_rows", 10)

In [2]:
colnames = ['Ref', 'AvgSupplyDelay']
new_purchase_data = pd.read_csv('Lokad_PurchaseOrders.csv').merge(pd.read_csv('Lokad_AverageSupplyDelay.csv', 
                                                            names = colnames, header = None), on = 'Ref', right_index = True)

new_purchase_data

,Unnamed: 0,Id,Loc,Ref,DeliveryDate,Quantity,Received,NetAmount,Supplier,PONumber,Date,Currency,SupplyDelay,AvgSupplyDelay
0,0,15641711/Los Angeles,Los Angeles,15641711,2016-06-22,50,50,164.999998,FHL,PO-200193,2016-04-20,USD,63 days 00:00:00.000000000,2277
1,1,15641711/Los Angeles,Los Angeles,15641711,2016-07-29,47,47,155.099998,FHL,PO-200243,2016-07-26,USD,3 days 00:00:00.000000000,2277
138,138,15641711/New-York,New-York,15641711,2016-12-04,800,800,2639.999960,FHL,PO-200121,2016-01-25,USD,314 days 00:00:00.000000000,2277
139,139,15641711/New-York,New-York,15641711,2001-01-01,100,0,329.999995,FHL,PO-200123,2016-01-26,USD,5503 days 00:00:00.000000000,2277
765,765,15641711/Chicago,Chicago,15641711,2001-01-01,100,0,329.999995,FHL,PO-200122,2016-01-26,USD,5503 days 00:00:00.000000000,2277
2,2,16075571/Los Angeles,Los Angeles,16075571,2016-06-22,100,100,300.000000,Logipro,PO-200193,2016-04-20,GBP,63 days 00:00:00.000000000,886
3,3,16075571/Los Angeles,Los Angeles,16075571,2016-07-29,300,300,900.000000,Logipro,PO-200243,2016-07-26,GBP,3 days 00:00:00.000000000,886
4,4,16075571/Los Angeles,Los Angeles,16075571,2001-01-01,121,0,363.000000,Logipro,PO-200271,2016-08-24,GBP,5714 days 00:00:00.000000000,886
140,140,16075571/New-York,New-York,16075571,2016-06-22,200,200,600.000000,Logipro,PO-200131,2016-09-02,GBP,72 days 00:00:00.000000000,886
141,141,16075571/New-York,New-York,16075571,2016-01-08,2400,2300,7200.000000,Logipro,PO-200240,2016-07-19,GBP,193 days 00:00:00.000000000,886
142,142,16075571/New-York,New-York,16075571,2016-05-08,2100,2100,6300.000000,Logipro,PO-200246,2016-07-28,GBP,81 days 00:00:00.000000000,886
766,766,16075571/Chicago,Chicago,16075571,2016-03-22,100,100,300.000000,Logipro,PO-200148,2016-01-03,GBP,79 days 00:00:00.000000000,886
5,5,14759689/Los Angeles,Los Angeles,14759689,2001-01-01,103,0,336.809998,Drecom,PO-200271,2016-08-24,GBP,5714 days 00:00:00.000000000,2047
143,143,14759689/New-York,New-York,14759689,2016-08-02,4000,4000,13079.999920,Drecom,PO-200101,2016-12-01,GBP,121 days 00:00:00.000000000,2047
767,767,14759689/Chicago,Chicago,14759689,2016-01-29,1000,1000,3269.999980,Drecom,PO-200103,2016-12-01,GBP,307 days 00:00:00.000000000,2047
6,6,14095459/Los Angeles,Los Angeles,14095459,2001-01-01,100,0,4654.999920,Drecom,PO-200225,2016-08-06,USD,5696 days 00:00:00.000000000,996
144,144,14095459/New-York,New-York,14095459,2015-10-28,3,3,139.649998,Drecom,PO-200031,2015-10-13,USD,15 days 00:00:00.000000000,996
145,145,14095459/New-York,New-York,14095459,2016-01-18,200,200,9309.999840,Drecom,PO-200088,2015-12-17,USD,32 days 00:00:00.000000000,996
146,146,14095459/New-York,New-York,14095459,2016-08-29,100,100,4654.999920,Drecom,PO-200178,2016-04-04,USD,147 days 00:00:00.000000000,996
768,768,14095459/Chicago,Chicago,14095459,2016-04-05,50,50,2327.499960,Drecom,PO-200147,2016-02-26,USD,39 days 00:00:00.000000000,996
769,769,14095459/Chicago,Chicago,14095459,2016-05-08,50,50,2327.499960,Drecom,PO-200165,2016-03-18,USD,51 days 00:00:00.000000000,996
7,7,15586718/Los Angeles,Los Angeles,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200225,2016-08-06,GBP,5696 days 00:00:00.000000000,2904
148,148,15586718/New-York,New-York,15586718,2016-01-18,14,14,798.000000,Drecom,PO-200088,2015-12-17,GBP,32 days 00:00:00.000000000,2904
149,149,15586718/New-York,New-York,15586718,2016-01-04,110,110,6270.000000,Drecom,PO-200118,2016-01-21,GBP,17 days 00:00:00.000000000,2904
150,150,15586718/New-York,New-York,15586718,2016-07-25,200,200,11400.000000,Drecom,PO-200164,2016-03-18,GBP,129 days 00:00:00.000000000,2904
151,151,15586718/New-York,New-York,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200284,2016-09-20,GBP,5741 days 00:00:00.000000000,2904
152,152,15586718/New-York,New-York,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200301,2016-10-26,GBP,5777 days 00:00:00.000000000,2904
770,770,15586718/Chicago,Chicago,15586718,2016-04-05,55,55,3135.000000,Drecom,PO-200147,2016-02-26,GBP,39 days 00:00:00.000000000,2904
771,771,15586718/Chicago,Chicago,15586718,2016-05-08,99,99,5643.000000,Drecom,PO-200165,2016-03-18,GBP,51 days 00:00:00.000000000,2904
772,772,15586718/Chicago,Chicago,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200285,2016-09-20,GBP,5741 days 00:00:00.000000000,2904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,1037,10132892/Chicago,Chicago,10132892,2016-06-20,12,12,556.560013,Drecom,PO-200192,2016-04-19,USD,62 days 00:00:00.000000000,669
680,680,14339722/New-York,New-York,14339722,2015-05-10,40,40,1762.799988,Drecom,PO-200009,2015-03-08,USD,63 days 00:00:00.000000000,80
681,681,14339722/New-York,New-York,14339722,2015-10-26,40,40,1762.799988,Drecom,PO-200017,2015-08-31,USD,56 days 00:00:00.000000000,80
682,682,14339722/New-York,New-York,14339722,2015-10-29,20,20,881.399994,Drecom,PO-200023,2015-09-15,USD,44 days 00:00:00.000000000,80
683,683,14339722/New-York,New-York,14339722,2016-06-01,20,20,881.399994,Drecom,PO-200038,2015-10-29,USD,216 days 00:00:00.000000000,80
684,684,14339722/New-York,New-York,14339722,2016-02-15,28,28,1233.959992,Drecom,PO-200090,2015-12-21,USD,56 days 00:00:00.000000000,80
685,685,14339722/New-York,New-York,14339722,2016-06-17,26,26,1145.819992,Drecom,PO-200191,2016-04-19,USD,59 days 00:00:00.000000000,80
686,686,14339722/New-York,New-York,14339722,2016-06-21,14,14,616.979996,Drecom,PO-200196,2016-04-25,USD,57 days 00:00:00.000000000,80
687,687,14339722/New-York,New-York,14339722,2016-06-23,20,20,881.399994,Drecom,PO-200198,2016-04-26,USD,58 days 00:00:00.000000000,80
688,688,14339722/New-York,New-York,14339722,2016-01-08,20,20,881.399994,Drecom,PO-200215,2016-02-06,USD,29 days 00:00:00.000000000,80
1038,1038,14339722/Chicago,Chicago,14339722,2015-12-22,12,12,528.839996,Drecom,PO-200044,2015-10-30,USD,53 days 00:00:00.000000000,80
1039,1039,14339722/Chicago,Chicago,14339722,2016-05-02,10,10,440.699997,Drecom,PO-200091,2015-12-22,USD,132 days 00:00:00.000000000,80
1040,1040,14339722/Chicago,Chicago,14339722,2016-07-26,40,40,1762.799988,Drecom,PO-200200,2016-03-05,USD,143 days 00:00:00.000000000,80
710,710,15963625/New-York,New-York,15963625,2015-10-26,30,30,883.500024,RRD,PO-200018,2015-01-09,USD,290 days 00:00:00.000000000,2448
711,711,15963625/New-York,New-York,15963625,2016-12-02,50,50,1472.500040,RRD,PO-200087,2015-12-17,USD,351 days 00:00:00.000000000,2448
712,712,15963625/New-York,New-York,15963625,2001-01-01,20,0,589.000016,RRD,PO-200280,2016-09-14,USD,5735 days 00:00:00.000000000,2448
1049,1049,15963625/Chicago,Chicago,15963625,2016-05-02,20,20,589.000016,RRD,PO-200091,2015-12-22,USD,132 days 00:00:00.000000000,2448
1050,1050,15963625/Chicago,Chicago,15963625,2001-01-01,10,0,294.500008,RRD,PO-200281,2016-09-15,USD,5736 days 00:00:00.000000000,2448
746,746,14404386/New-York,New-York,14404386,2015-11-11,20,20,1266.200028,Drecom,PO-200024,2015-09-22,GBP,50 days 00:00:00.000000000,1500
747,747,14404386/New-York,New-York,14404386,2015-12-31,36,36,2279.160050,Drecom,PO-200034,2015-10-22,GBP,70 days 00:00:00.000000000,1500
748,748,14404386/New-York,New-York,14404386,2016-01-18,16,16,1012.960022,Drecom,PO-200059,2015-11-18,GBP,61 days 00:00:00.000000000,1500
749,749,14404386/New-York,New-York,14404386,2016-02-18,12,12,759.720017,Drecom,PO-200083,2015-12-15,GBP,65 days 00:00:00.000000000,1500
750,750,14404386/New-York,New-York,14404386,2016-06-21,30,30,1899.300042,Drecom,PO-200196,2016-04-25,GBP,57 days 00:00:00.000000000,1500
751,751,14404386/New-York,New-York,14404386,2016-07-26,20,20,1266.200028,Drecom,PO-200204,2016-12-05,GBP,132 days 00:00:00.000000000,1500
752,752,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200293,2016-04-10,GBP,5578 days 00:00:00.000000000,1500
753,753,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200297,2016-10-19,GBP,5770 days 00:00:00.000000000,1500
1066,1066,14404386/Chicago,Chicago,14404386,2016-01-18,10,10,633.100014,Drecom,PO-200074,2015-03-12,GBP,312 days 00:00:00.000000000,1500
1067,1067,14404386/Chicago,Chicago,14404386,2016-06-05,10,10,633.100014,Drecom,PO-200160,2016-03-15,GBP,82 days 00:00:00.000000000,1500
1068,1068,14404386/Chicago,Chicago,14404386,2016-06-20,20,20,1266.200028,Drecom,PO-200192,2016-04-19,GBP,62 days 00:00:00.000000000,1500
1069,1069,14404386/Chicago,Chicago,14404386,2001-01-01,16,0,1012.960022,Drecom,PO-200298,2016-10-20,GBP,5771 days 00:00:00.000000000,1500

In [3]:
# For the Avarage daily usage of product is calculated using the Lokad_Orders dataset 

lokad_orders = pd.read_csv('Lokad_Orders.csv')
lokad_orders

,Id,Ref,Loc,Date,Quantity,NetAmount,OrderId,Currency,Client
0,10014552/Chicago,10014552,Chicago,2013-04-04,1,135.800003,197706006,USD,17538
1,10014552/Chicago,10014552,Chicago,2013-04-13,1,135.800003,199542006,USD,73244
2,10014552/Chicago,10014552,Chicago,2013-04-14,1,141.029999,199709006,USD,92848
3,10014552/Chicago,10014552,Chicago,2013-05-09,1,135.800003,205089006,USD,85193
4,10014552/Chicago,10014552,Chicago,2013-07-23,1,129.440002,221346006,USD,32938
5,10014552/Chicago,10014552,Chicago,2013-08-11,1,129.440002,226242006,USD,69304
6,10014552/Chicago,10014552,Chicago,2013-08-26,1,135.800003,230208006,USD,55364
7,10014552/Chicago,10014552,Chicago,2013-10-07,1,129.440002,240655006,USD,7119
8,10014552/Chicago,10014552,Chicago,2013-10-25,1,141.029999,245311006,USD,13709
9,10014552/Chicago,10014552,Chicago,2013-10-26,1,141.029999,245556006,USD,43837
10,10014552/Chicago,10014552,Chicago,2013-11-08,1,129.440002,249200006,USD,53783
11,10014552/Chicago,10014552,Chicago,2014-01-17,1,78.639999,268799006,USD,67387
12,10014552/Chicago,10014552,Chicago,2014-01-20,1,129.440002,269341006,USD,29242
13,10014552/Chicago,10014552,Chicago,2014-02-22,1,124.589996,113-5664422-1821816,USD,63311
14,10014552/Chicago,10014552,Chicago,2014-03-04,1,119.139999,105-0697420-8292208,USD,98970
15,10014552/Chicago,10014552,Chicago,2014-04-03,1,129.440002,293045006,USD,28577
16,10014552/Chicago,10014552,Chicago,2014-05-24,1,78.639999,306787006,USD,25494
17,10014552/Chicago,10014552,Chicago,2014-05-30,1,136.380005,308145006,USD,42560
18,10014552/Chicago,10014552,Chicago,2014-09-08,1,129.440002,332256006,USD,34008
19,10014552/Chicago,10014552,Chicago,2014-11-29,1,136.380005,357297006,USD,9116
20,10014552/Chicago,10014552,Chicago,2015-01-11,1,134.800003,369454006,USD,61314
21,10014552/Chicago,10014552,Chicago,2015-03-06,1,129.440002,385266006,USD,3023
22,10014552/Chicago,10014552,Chicago,2015-04-09,1,129.440002,396211006,USD,66865
23,10014552/Chicago,10014552,Chicago,2015-07-14,1,129.440002,420063006,USD,72101
24,10014552/Chicago,10014552,Chicago,2015-08-02,1,129.440002,425440006,USD,93181
25,10014552/Chicago,10014552,Chicago,2015-08-04,1,129.440002,426019006,USD,63197
26,10014552/Chicago,10014552,Chicago,2015-08-30,1,129.440002,432884006,USD,74882
27,10014552/Chicago,10014552,Chicago,2015-09-01,1,129.440002,433581006,USD,16695
28,10014552/Chicago,10014552,Chicago,2015-10-25,1,132.290009,448117006,USD,95543
29,10014552/Chicago,10014552,Chicago,2015-10-28,1,139.449997,448776006,USD,17060
...,...,...,...,...,...,...,...,...,...
119630,9952426/New-York,9952426,New-York,2016-02-28,1,189.510010,HD-156758,USD,58060
119631,9952426/New-York,9952426,New-York,2016-02-28,1,189.510010,HD-156757,USD,74952
119632,9952426/New-York,9952426,New-York,2016-03-07,1,189.510010,SC-459870477,USD,45795
119633,9952426/New-York,9952426,New-York,2016-03-10,1,189.510010,HD-157989,USD,84156
119634,9952426/New-York,9952426,New-York,2016-05-12,1,68.400002,SC-464704001,USD,28698
119635,9952426/New-York,9952426,New-York,2016-05-21,1,284.269989,HD-163365,USD,5118
119636,9952426/New-York,9952426,New-York,2016-05-25,1,189.510010,HD-163669,USD,3398
119637,9952426/New-York,9952426,New-York,2016-05-27,1,191.570007,HD-163851,USD,51294
119638,9952426/New-York,9952426,New-York,2016-06-03,1,189.510010,100001288,USD,77256
119639,9952426/New-York,9952426,New-York,2016-06-04,1,81.349998,HD-164465,USD,9393
119640,9952426/New-York,9952426,New-York,2016-06-08,1,191.710007,100001331,USD,20280
119641,9952426/New-York,9952426,New-York,2016-06-10,1,81.349998,HD-164915,USD,68926
119642,9952426/New-York,9952426,New-York,2016-06-22,1,176.559998,SC-467448700,USD,36497
119643,9952426/New-York,9952426,New-York,2016-06-29,1,176.559998,SC-467903015,USD,57789
119644,9952426/New-York,9952426,New-York,2016-07-02,1,81.349998,HD-166920,USD,55708
119645,9952426/New-York,9952426,New-York,2016-07-05,1,81.349998,HD-167121,USD,75377
119646,9952426/New-York,9952426,New-York,2016-07-05,1,81.349998,HD-167090,USD,12886
119647,9952426/New-York,9952426,New-York,2016-07-05,1,189.510010,HD-167186,USD,14323
119648,9952426/New-York,9952426,New-York,2016-07-11,1,81.349998,SC-468635401,USD,31862
119649,9952426/New-York,9952426,New-York,2016-07-11,1,68.400002,SC-468627933,USD,82063
119650,9952426/New-York,9952426,New-York,2016-07-20,1,189.510010,HD-168635,USD,69570
119651,9952426/New-York,9952426,New-York,2016-07-30,1,189.510010,HD-169586,USD,71811
119652,9952426/New-York,9952426,New-York,2016-08-01,1,68.400002,SC-470084055,USD,67100
119653,9952426/New-York,9952426,New-York,2016-08-07,1,189.510010,HD-170425,USD,69827
119654,9952426/New-York,9952426,New-York,2016-08-15,1,189.510010,HD-171286,USD,70801
119655,9952426/New-York,9952426,New-York,2016-08-16,1,81.349998,HD-171401,USD,92811
119656,9952426/New-York,9952426,New-York,2016-09-09,1,68.400002,SC-472670440,USD,28745
119657,9952426/New-York,9952426,New-York,2016-09-13,1,81.349998,HD-174116,USD,71380
119658,9952426/New-York,9952426,New-York,2016-09-18,1,81.349998,HD-174633,USD,19839
119659,9952426/New-York,9952426,New-York,2016-09-20,1,68.400002,SC-475391720,USD,98212

In [4]:
# Average daily usage sorted on the basis of Reference of the product.
#def avg_usage():
avg_daily_usage = lokad_orders.groupby('Ref')['Quantity'].mean().astype(int)
    #return avg_daily_usage
avg_daily_usage.to_csv('Quantity.csv')

In [5]:
colnames = ['Ref', 'DailyUsage']
data = pd.read_csv('Quantity.csv', names = colnames, header = None)

data

          Ref  DailyUsage
0     9952426           1
1    10014552           1
2    10095232           1
3    10099950           1
4    10132892           1
5    10136626           1
6    10210677           1
7    10255812           4
8    10422793           1
9    10592438           1
10   10595489           1
11   10678449           1
12   10764226           1
13   11045096           1
14   11097836           1
15   11481389           1
16   11557472           1
17   11635178           1
18   11711100           1
19   11711150           1
20   11711636           1
21   11780124           1
22   11788268           1
23   11800905           1
24   11906239           1
25   11914966           1
26   11929369           1
27   11941800           1
28   12401265           1
29   12407652           1
..        ...         ...
76   14820865           1
77   14895172           1
78   14901389           1
79   14993287           1
80   15034737           1
81   15063964           1
82   15092233           1
83   15149291           1
84   15343952           1
85   15410849           1
86   15416092           1
87   15431986           1
88   15519926           1
89   15586718           1
90   15641711           1
91   15808622           1
92   15880950           1
93   15963625           1
94   16018733           1
95   16075571           1
96   16089695           1
97   16187687           1
98   16188573           1
99   16239251           1
100  16277400           1
101  16363786           1
102  16401974           1
103  16412231           1
104  16430058           3
105  16595101           1

[106 rows x 2 columns]

In [12]:
new_data = new_purchase_data.merge(data, on = 'Ref', right_index = True)
new_data

,Unnamed: 0,Id,Loc,Ref,DeliveryDate,Quantity,Received,NetAmount,Supplier,PONumber,Date,Currency,SupplyDelay,AvgSupplyDelay,DailyUsage
0,0,15641711/Los Angeles,Los Angeles,15641711,2016-06-22,50,50,164.999998,FHL,PO-200193,2016-04-20,USD,63 days 00:00:00.000000000,2277,1
1,1,15641711/Los Angeles,Los Angeles,15641711,2016-07-29,47,47,155.099998,FHL,PO-200243,2016-07-26,USD,3 days 00:00:00.000000000,2277,1
138,138,15641711/New-York,New-York,15641711,2016-12-04,800,800,2639.999960,FHL,PO-200121,2016-01-25,USD,314 days 00:00:00.000000000,2277,1
139,139,15641711/New-York,New-York,15641711,2001-01-01,100,0,329.999995,FHL,PO-200123,2016-01-26,USD,5503 days 00:00:00.000000000,2277,1
765,765,15641711/Chicago,Chicago,15641711,2001-01-01,100,0,329.999995,FHL,PO-200122,2016-01-26,USD,5503 days 00:00:00.000000000,2277,1
2,2,16075571/Los Angeles,Los Angeles,16075571,2016-06-22,100,100,300.000000,Logipro,PO-200193,2016-04-20,GBP,63 days 00:00:00.000000000,886,1
3,3,16075571/Los Angeles,Los Angeles,16075571,2016-07-29,300,300,900.000000,Logipro,PO-200243,2016-07-26,GBP,3 days 00:00:00.000000000,886,1
4,4,16075571/Los Angeles,Los Angeles,16075571,2001-01-01,121,0,363.000000,Logipro,PO-200271,2016-08-24,GBP,5714 days 00:00:00.000000000,886,1
140,140,16075571/New-York,New-York,16075571,2016-06-22,200,200,600.000000,Logipro,PO-200131,2016-09-02,GBP,72 days 00:00:00.000000000,886,1
141,141,16075571/New-York,New-York,16075571,2016-01-08,2400,2300,7200.000000,Logipro,PO-200240,2016-07-19,GBP,193 days 00:00:00.000000000,886,1
142,142,16075571/New-York,New-York,16075571,2016-05-08,2100,2100,6300.000000,Logipro,PO-200246,2016-07-28,GBP,81 days 00:00:00.000000000,886,1
766,766,16075571/Chicago,Chicago,16075571,2016-03-22,100,100,300.000000,Logipro,PO-200148,2016-01-03,GBP,79 days 00:00:00.000000000,886,1
5,5,14759689/Los Angeles,Los Angeles,14759689,2001-01-01,103,0,336.809998,Drecom,PO-200271,2016-08-24,GBP,5714 days 00:00:00.000000000,2047,1
143,143,14759689/New-York,New-York,14759689,2016-08-02,4000,4000,13079.999920,Drecom,PO-200101,2016-12-01,GBP,121 days 00:00:00.000000000,2047,1
767,767,14759689/Chicago,Chicago,14759689,2016-01-29,1000,1000,3269.999980,Drecom,PO-200103,2016-12-01,GBP,307 days 00:00:00.000000000,2047,1
6,6,14095459/Los Angeles,Los Angeles,14095459,2001-01-01,100,0,4654.999920,Drecom,PO-200225,2016-08-06,USD,5696 days 00:00:00.000000000,996,1
144,144,14095459/New-York,New-York,14095459,2015-10-28,3,3,139.649998,Drecom,PO-200031,2015-10-13,USD,15 days 00:00:00.000000000,996,1
145,145,14095459/New-York,New-York,14095459,2016-01-18,200,200,9309.999840,Drecom,PO-200088,2015-12-17,USD,32 days 00:00:00.000000000,996,1
146,146,14095459/New-York,New-York,14095459,2016-08-29,100,100,4654.999920,Drecom,PO-200178,2016-04-04,USD,147 days 00:00:00.000000000,996,1
768,768,14095459/Chicago,Chicago,14095459,2016-04-05,50,50,2327.499960,Drecom,PO-200147,2016-02-26,USD,39 days 00:00:00.000000000,996,1
769,769,14095459/Chicago,Chicago,14095459,2016-05-08,50,50,2327.499960,Drecom,PO-200165,2016-03-18,USD,51 days 00:00:00.000000000,996,1
7,7,15586718/Los Angeles,Los Angeles,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200225,2016-08-06,GBP,5696 days 00:00:00.000000000,2904,1
148,148,15586718/New-York,New-York,15586718,2016-01-18,14,14,798.000000,Drecom,PO-200088,2015-12-17,GBP,32 days 00:00:00.000000000,2904,1
149,149,15586718/New-York,New-York,15586718,2016-01-04,110,110,6270.000000,Drecom,PO-200118,2016-01-21,GBP,17 days 00:00:00.000000000,2904,1
150,150,15586718/New-York,New-York,15586718,2016-07-25,200,200,11400.000000,Drecom,PO-200164,2016-03-18,GBP,129 days 00:00:00.000000000,2904,1
151,151,15586718/New-York,New-York,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200284,2016-09-20,GBP,5741 days 00:00:00.000000000,2904,1
152,152,15586718/New-York,New-York,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200301,2016-10-26,GBP,5777 days 00:00:00.000000000,2904,1
770,770,15586718/Chicago,Chicago,15586718,2016-04-05,55,55,3135.000000,Drecom,PO-200147,2016-02-26,GBP,39 days 00:00:00.000000000,2904,1
771,771,15586718/Chicago,Chicago,15586718,2016-05-08,99,99,5643.000000,Drecom,PO-200165,2016-03-18,GBP,51 days 00:00:00.000000000,2904,1
772,772,15586718/Chicago,Chicago,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200285,2016-09-20,GBP,5741 days 00:00:00.000000000,2904,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,1037,10132892/Chicago,Chicago,10132892,2016-06-20,12,12,556.560013,Drecom,PO-200192,2016-04-19,USD,62 days 00:00:00.000000000,669,1
680,680,14339722/New-York,New-York,14339722,2015-05-10,40,40,1762.799988,Drecom,PO-200009,2015-03-08,USD,63 days 00:00:00.000000000,80,1
681,681,14339722/New-York,New-York,14339722,2015-10-26,40,40,1762.799988,Drecom,PO-200017,2015-08-31,USD,56 days 00:00:00.000000000,80,1
682,682,14339722/New-York,New-York,14339722,2015-10-29,20,20,881.399994,Drecom,PO-200023,2015-09-15,USD,44 days 00:00:00.000000000,80,1
683,683,14339722/New-York,New-York,14339722,2016-06-01,20,20,881.399994,Drecom,PO-200038,2015-10-29,USD,216 days 00:00:00.000000000,80,1
684,684,14339722/New-York,New-York,14339722,2016-02-15,28,28,1233.959992,Drecom,PO-200090,2015-12-21,USD,56 days 00:00:00.000000000,80,1
685,685,14339722/New-York,New-York,14339722,2016-06-17,26,26,1145.819992,Drecom,PO-200191,2016-04-19,USD,59 days 00:00:00.000000000,80,1
686,686,14339722/New-York,New-York,14339722,2016-06-21,14,14,616.979996,Drecom,PO-200196,2016-04-25,USD,57 days 00:00:00.000000000,80,1
687,687,14339722/New-York,New-York,14339722,2016-06-23,20,20,881.399994,Drecom,PO-200198,2016-04-26,USD,58 days 00:00:00.000000000,80,1
688,688,14339722/New-York,New-York,14339722,2016-01-08,20,20,881.399994,Drecom,PO-200215,2016-02-06,USD,29 days 00:00:00.000000000,80,1
1038,1038,14339722/Chicago,Chicago,14339722,2015-12-22,12,12,528.839996,Drecom,PO-200044,2015-10-30,USD,53 days 00:00:00.000000000,80,1
1039,1039,14339722/Chicago,Chicago,14339722,2016-05-02,10,10,440.699997,Drecom,PO-200091,2015-12-22,USD,132 days 00:00:00.000000000,80,1
1040,1040,14339722/Chicago,Chicago,14339722,2016-07-26,40,40,1762.799988,Drecom,PO-200200,2016-03-05,USD,143 days 00:00:00.000000000,80,1
710,710,15963625/New-York,New-York,15963625,2015-10-26,30,30,883.500024,RRD,PO-200018,2015-01-09,USD,290 days 00:00:00.000000000,2448,1
711,711,15963625/New-York,New-York,15963625,2016-12-02,50,50,1472.500040,RRD,PO-200087,2015-12-17,USD,351 days 00:00:00.000000000,2448,1
712,712,15963625/New-York,New-York,15963625,2001-01-01,20,0,589.000016,RRD,PO-200280,2016-09-14,USD,5735 days 00:00:00.000000000,2448,1
1049,1049,15963625/Chicago,Chicago,15963625,2016-05-02,20,20,589.000016,RRD,PO-200091,2015-12-22,USD,132 days 00:00:00.000000000,2448,1
1050,1050,15963625/Chicago,Chicago,15963625,2001-01-01,10,0,294.500008,RRD,PO-200281,2016-09-15,USD,5736 days 00:00:00.000000000,2448,1
746,746,14404386/New-York,New-York,14404386,2015-11-11,20,20,1266.200028,Drecom,PO-200024,2015-09-22,GBP,50 days 00:00:00.000000000,1500,1
747,747,14404386/New-York,New-York,14404386,2015-12-31,36,36,2279.160050,Drecom,PO-200034,2015-10-22,GBP,70 days 00:00:00.000000000,1500,1
748,748,14404386/New-York,New-York,14404386,2016-01-18,16,16,1012.960022,Drecom,PO-200059,2015-11-18,GBP,61 days 00:00:00.000000000,1500,1
749,749,14404386/New-York,New-York,14404386,2016-02-18,12,12,759.720017,Drecom,PO-200083,2015-12-15,GBP,65 days 00:00:00.000000000,1500,1
750,750,14404386/New-York,New-York,14404386,2016-06-21,30,30,1899.300042,Drecom,PO-200196,2016-04-25,GBP,57 days 00:00:00.000000000,1500,1
751,751,14404386/New-York,New-York,14404386,2016-07-26,20,20,1266.200028,Drecom,PO-200204,2016-12-05,GBP,132 days 00:00:00.000000000,1500,1
752,752,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200293,2016-04-10,GBP,5578 days 00:00:00.000000000,1500,1
753,753,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200297,2016-10-19,GBP,5770 days 00:00:00.000000000,1500,1
1066,1066,14404386/Chicago,Chicago,14404386,2016-01-18,10,10,633.100014,Drecom,PO-200074,2015-03-12,GBP,312 days 00:00:00.000000000,1500,1
1067,1067,14404386/Chicago,Chicago,14404386,2016-06-05,10,10,633.100014,Drecom,PO-200160,2016-03-15,GBP,82 days 00:00:00.000000000,1500,1
1068,1068,14404386/Chicago,Chicago,14404386,2016-06-20,20,20,1266.200028,Drecom,PO-200192,2016-04-19,GBP,62 days 00:00:00.000000000,1500,1
1069,1069,14404386/Chicago,Chicago,14404386,2001-01-01,16,0,1012.960022,Drecom,PO-200298,2016-10-20,GBP,5771 days 00:00:00.000000000,1500,1

In [53]:
new_data['Demand'] = new_data.AvgSupplyDelay * new_data.DailyUsage
Avg_lead_demand = new_data.groupby('Ref')['Demand'].mean()

In [54]:
Avg_lead_demand

Ref
9952426       58
10014552    1421
10095232     144
10099950    2213
10132892     669
10136626     885
10210677    1049
10255812    3544
10422793      85
10592438     783
10595489     670
10678449    1988
10764226      69
11045096    2335
11097836     946
11481389    1200
11557472     150
11635178      58
11711100    1981
11711636    1133
11780124    2444
11788268    1049
11800905      92
11906239    1049
11914966     629
11929369    2115
11941800    1133
12401265     160
12409642    1968
12451991    1159
            ...
14789055     979
14820865      92
14895172     114
14901389      32
15034737    1325
15063964     895
15092233     992
15149291     869
15343952    1915
15410849    1746
15416092    2103
15431986    1657
15519926    1493
15586718    2904
15641711    2277
15808622     702
15880950    1402
15963625    2448
16018733    1197
16075571     886
16089695     783
16187687    2163
16188573    1224
16239251    1543
16277400    1159
16363786    1452
16401974     933
16412231    1217
16430058    3006
16595101    1021
Name: Demand, Length: 100, dtype: int64