## Lokad_Orders

This file contains the historical sales data
ID: the SKU (Stock keeping Unit) identifier (value: 10014552/Chicago)
Loc: the identifier of the geographical location (value: Chicago)
Ref: the identifier of the product (value: 10014552)
Date: ordering date (value: 4/4/2013 for some cases the values are missing)
Quantity: quantity ordered in units (value: 1)
NetAmount: amount paid for order (value: 135.8)
OrderId: unique identifier for the customer order (value: 1.98E+08)
Currency: code for the currency(value : USD)
Client: a client indentifier (value: 17538)

Lead Demand: The projected level of demand for a product from consumers during its lead time from the supplier to the retailer

For our calaculation, 

Lead Demand(LD) = LeadTime(LT in days) * Avg Daily usage(of product in days)

In our case Leasd Time is sam as AvgSupplyDelay as the reorder delay in our case is zero for the time being.

## Reading the csv files

In [1]:
% matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#pd.get_option("display.max_rows", 10)

In [2]:
colnames = ['Ref', 'AvgSupplyDelay']
new_purchase_data = pd.read_csv('temp1.csv')

new_purchase_data

,Unnamed: 0,Unnamed: 0.1,Id,Loc,Ref,DeliveryDate,Quantity,Received,NetAmount,Supplier,PONumber,Date,Currency,LeadTime,AvgLT,sigmaLT
0,0,0,15641711/Los Angeles,Los Angeles,15641711,2016-06-22,50,50,164.999998,FHL,PO-200193,2016-04-20,USD,63,2277,2947
1,1,1,15641711/Los Angeles,Los Angeles,15641711,2016-07-29,47,47,155.099998,FHL,PO-200243,2016-07-26,USD,3,2277,2947
2,2,138,15641711/New-York,New-York,15641711,2016-12-04,800,800,2639.999960,FHL,PO-200121,2016-01-25,USD,314,2277,2947
3,3,139,15641711/New-York,New-York,15641711,2001-01-01,100,0,329.999995,FHL,PO-200123,2016-01-26,USD,5503,2277,2947
4,4,765,15641711/Chicago,Chicago,15641711,2001-01-01,100,0,329.999995,FHL,PO-200122,2016-01-26,USD,5503,2277,2947
5,5,2,16075571/Los Angeles,Los Angeles,16075571,2016-06-22,100,100,300.000000,Logipro,PO-200193,2016-04-20,GBP,63,886,2129
6,6,3,16075571/Los Angeles,Los Angeles,16075571,2016-07-29,300,300,900.000000,Logipro,PO-200243,2016-07-26,GBP,3,886,2129
7,7,4,16075571/Los Angeles,Los Angeles,16075571,2001-01-01,121,0,363.000000,Logipro,PO-200271,2016-08-24,GBP,5714,886,2129
8,8,140,16075571/New-York,New-York,16075571,2016-06-22,200,200,600.000000,Logipro,PO-200131,2016-09-02,GBP,72,886,2129
9,9,141,16075571/New-York,New-York,16075571,2016-01-08,2400,2300,7200.000000,Logipro,PO-200240,2016-07-19,GBP,193,886,2129
10,10,142,16075571/New-York,New-York,16075571,2016-05-08,2100,2100,6300.000000,Logipro,PO-200246,2016-07-28,GBP,81,886,2129
11,11,766,16075571/Chicago,Chicago,16075571,2016-03-22,100,100,300.000000,Logipro,PO-200148,2016-01-03,GBP,79,886,2129
12,12,5,14759689/Los Angeles,Los Angeles,14759689,2001-01-01,103,0,336.809998,Drecom,PO-200271,2016-08-24,GBP,5714,2047,3176
13,13,143,14759689/New-York,New-York,14759689,2016-08-02,4000,4000,13079.999920,Drecom,PO-200101,2016-12-01,GBP,121,2047,3176
14,14,767,14759689/Chicago,Chicago,14759689,2016-01-29,1000,1000,3269.999980,Drecom,PO-200103,2016-12-01,GBP,307,2047,3176
15,15,6,14095459/Los Angeles,Los Angeles,14095459,2001-01-01,100,0,4654.999920,Drecom,PO-200225,2016-08-06,USD,5696,996,2302
16,16,144,14095459/New-York,New-York,14095459,2015-10-28,3,3,139.649998,Drecom,PO-200031,2015-10-13,USD,15,996,2302
17,17,145,14095459/New-York,New-York,14095459,2016-01-18,200,200,9309.999840,Drecom,PO-200088,2015-12-17,USD,32,996,2302
18,18,146,14095459/New-York,New-York,14095459,2016-08-29,100,100,4654.999920,Drecom,PO-200178,2016-04-04,USD,147,996,2302
19,19,768,14095459/Chicago,Chicago,14095459,2016-04-05,50,50,2327.499960,Drecom,PO-200147,2016-02-26,USD,39,996,2302
20,20,769,14095459/Chicago,Chicago,14095459,2016-05-08,50,50,2327.499960,Drecom,PO-200165,2016-03-18,USD,51,996,2302
21,21,7,15586718/Los Angeles,Los Angeles,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200225,2016-08-06,GBP,5696,2904,3005
22,22,148,15586718/New-York,New-York,15586718,2016-01-18,14,14,798.000000,Drecom,PO-200088,2015-12-17,GBP,32,2904,3005
23,23,149,15586718/New-York,New-York,15586718,2016-01-04,110,110,6270.000000,Drecom,PO-200118,2016-01-21,GBP,17,2904,3005
24,24,150,15586718/New-York,New-York,15586718,2016-07-25,200,200,11400.000000,Drecom,PO-200164,2016-03-18,GBP,129,2904,3005
25,25,151,15586718/New-York,New-York,15586718,2001-01-01,200,0,11400.000000,Drecom,PO-200284,2016-09-20,GBP,5741,2904,3005
26,26,152,15586718/New-York,New-York,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200301,2016-10-26,GBP,5777,2904,3005
27,27,770,15586718/Chicago,Chicago,15586718,2016-04-05,55,55,3135.000000,Drecom,PO-200147,2016-02-26,GBP,39,2904,3005
28,28,771,15586718/Chicago,Chicago,15586718,2016-05-08,99,99,5643.000000,Drecom,PO-200165,2016-03-18,GBP,51,2904,3005
29,29,772,15586718/Chicago,Chicago,15586718,2001-01-01,100,0,5700.000000,Drecom,PO-200285,2016-09-20,GBP,5741,2904,3005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,1046,1037,10132892/Chicago,Chicago,10132892,2016-06-20,12,12,556.560013,Drecom,PO-200192,2016-04-19,USD,62,669,1793
1047,1047,680,14339722/New-York,New-York,14339722,2015-05-10,40,40,1762.799988,Drecom,PO-200009,2015-03-08,USD,63,80,54
1048,1048,681,14339722/New-York,New-York,14339722,2015-10-26,40,40,1762.799988,Drecom,PO-200017,2015-08-31,USD,56,80,54
1049,1049,682,14339722/New-York,New-York,14339722,2015-10-29,20,20,881.399994,Drecom,PO-200023,2015-09-15,USD,44,80,54
1050,1050,683,14339722/New-York,New-York,14339722,2016-06-01,20,20,881.399994,Drecom,PO-200038,2015-10-29,USD,216,80,54
1051,1051,684,14339722/New-York,New-York,14339722,2016-02-15,28,28,1233.959992,Drecom,PO-200090,2015-12-21,USD,56,80,54
1052,1052,685,14339722/New-York,New-York,14339722,2016-06-17,26,26,1145.819992,Drecom,PO-200191,2016-04-19,USD,59,80,54
1053,1053,686,14339722/New-York,New-York,14339722,2016-06-21,14,14,616.979996,Drecom,PO-200196,2016-04-25,USD,57,80,54
1054,1054,687,14339722/New-York,New-York,14339722,2016-06-23,20,20,881.399994,Drecom,PO-200198,2016-04-26,USD,58,80,54
1055,1055,688,14339722/New-York,New-York,14339722,2016-01-08,20,20,881.399994,Drecom,PO-200215,2016-02-06,USD,29,80,54
1056,1056,1038,14339722/Chicago,Chicago,14339722,2015-12-22,12,12,528.839996,Drecom,PO-200044,2015-10-30,USD,53,80,54
1057,1057,1039,14339722/Chicago,Chicago,14339722,2016-05-02,10,10,440.699997,Drecom,PO-200091,2015-12-22,USD,132,80,54
1058,1058,1040,14339722/Chicago,Chicago,14339722,2016-07-26,40,40,1762.799988,Drecom,PO-200200,2016-03-05,USD,143,80,54
1059,1059,710,15963625/New-York,New-York,15963625,2015-10-26,30,30,883.500024,RRD,PO-200018,2015-01-09,USD,290,2448,3001
1060,1060,711,15963625/New-York,New-York,15963625,2016-12-02,50,50,1472.500040,RRD,PO-200087,2015-12-17,USD,351,2448,3001
1061,1061,712,15963625/New-York,New-York,15963625,2001-01-01,20,0,589.000016,RRD,PO-200280,2016-09-14,USD,5735,2448,3001
1062,1062,1049,15963625/Chicago,Chicago,15963625,2016-05-02,20,20,589.000016,RRD,PO-200091,2015-12-22,USD,132,2448,3001
1063,1063,1050,15963625/Chicago,Chicago,15963625,2001-01-01,10,0,294.500008,RRD,PO-200281,2016-09-15,USD,5736,2448,3001
1064,1064,746,14404386/New-York,New-York,14404386,2015-11-11,20,20,1266.200028,Drecom,PO-200024,2015-09-22,GBP,50,1500,2537
1065,1065,747,14404386/New-York,New-York,14404386,2015-12-31,36,36,2279.160050,Drecom,PO-200034,2015-10-22,GBP,70,1500,2537
1066,1066,748,14404386/New-York,New-York,14404386,2016-01-18,16,16,1012.960022,Drecom,PO-200059,2015-11-18,GBP,61,1500,2537
1067,1067,749,14404386/New-York,New-York,14404386,2016-02-18,12,12,759.720017,Drecom,PO-200083,2015-12-15,GBP,65,1500,2537
1068,1068,750,14404386/New-York,New-York,14404386,2016-06-21,30,30,1899.300042,Drecom,PO-200196,2016-04-25,GBP,57,1500,2537
1069,1069,751,14404386/New-York,New-York,14404386,2016-07-26,20,20,1266.200028,Drecom,PO-200204,2016-12-05,GBP,132,1500,2537
1070,1070,752,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200293,2016-04-10,GBP,5578,1500,2537
1071,1071,753,14404386/New-York,New-York,14404386,2001-01-01,30,0,1899.300042,Drecom,PO-200297,2016-10-19,GBP,5770,1500,2537
1072,1072,1066,14404386/Chicago,Chicago,14404386,2016-01-18,10,10,633.100014,Drecom,PO-200074,2015-03-12,GBP,312,1500,2537
1073,1073,1067,14404386/Chicago,Chicago,14404386,2016-06-05,10,10,633.100014,Drecom,PO-200160,2016-03-15,GBP,82,1500,2537
1074,1074,1068,14404386/Chicago,Chicago,14404386,2016-06-20,20,20,1266.200028,Drecom,PO-200192,2016-04-19,GBP,62,1500,2537
1075,1075,1069,14404386/Chicago,Chicago,14404386,2001-01-01,16,0,1012.960022,Drecom,PO-200298,2016-10-20,GBP,5771,1500,2537

## Loading the data from Orders.csv

In [3]:
# For the Avarage daily usage of product is calculated using the Lokad_Orders dataset 

lokad_orders = pd.read_csv('Lokad_Orders.csv')
lokad_orders

,Id,Ref,Loc,Date,Quantity,NetAmount,OrderId,Currency,Client
0,10014552/Chicago,10014552,Chicago,4/4/2013,4,135.800003,197706006,USD,17538
1,10014552/Chicago,10014552,Chicago,4/13/2013,4,135.800003,199542006,USD,73244
2,10014552/Chicago,10014552,Chicago,4/14/2013,4,141.029999,199709006,USD,92848
3,10014552/Chicago,10014552,Chicago,5/9/2013,4,135.800003,205089006,USD,85193
4,10014552/Chicago,10014552,Chicago,7/23/2013,4,129.440002,221346006,USD,32938
5,10014552/Chicago,10014552,Chicago,8/11/2013,4,129.440002,226242006,USD,69304
6,10014552/Chicago,10014552,Chicago,8/26/2013,4,135.800003,230208006,USD,55364
7,10014552/Chicago,10014552,Chicago,10/7/2013,4,129.440002,240655006,USD,7119
8,10014552/Chicago,10014552,Chicago,10/25/2013,4,141.029999,245311006,USD,13709
9,10014552/Chicago,10014552,Chicago,10/26/2013,4,141.029999,245556006,USD,43837
10,10014552/Chicago,10014552,Chicago,11/8/2013,2,129.440002,249200006,USD,53783
11,10014552/Chicago,10014552,Chicago,1/17/2014,4,78.639999,268799006,USD,67387
12,10014552/Chicago,10014552,Chicago,1/20/2014,4,129.440002,269341006,USD,29242
13,10014552/Chicago,10014552,Chicago,2/22/2014,4,124.589996,113-5664422-1821816,USD,63311
14,10014552/Chicago,10014552,Chicago,3/4/2014,4,119.139999,105-0697420-8292208,USD,98970
15,10014552/Chicago,10014552,Chicago,4/3/2014,4,129.440002,293045006,USD,28577
16,10014552/Chicago,10014552,Chicago,5/24/2014,2,78.639999,306787006,USD,25494
17,10014552/Chicago,10014552,Chicago,5/30/2014,2,136.380005,308145006,USD,42560
18,10014552/Chicago,10014552,Chicago,9/8/2014,2,129.440002,332256006,USD,34008
19,10014552/Chicago,10014552,Chicago,11/29/2014,4,136.380005,357297006,USD,9116
20,10014552/Chicago,10014552,Chicago,1/11/2015,4,134.800003,369454006,USD,61314
21,10014552/Chicago,10014552,Chicago,3/6/2015,4,129.440002,385266006,USD,3023
22,10014552/Chicago,10014552,Chicago,4/9/2015,4,129.440002,396211006,USD,66865
23,10014552/Chicago,10014552,Chicago,7/14/2015,4,129.440002,420063006,USD,72101
24,10014552/Chicago,10014552,Chicago,8/2/2015,4,129.440002,425440006,USD,93181
25,10014552/Chicago,10014552,Chicago,8/4/2015,4,129.440002,426019006,USD,63197
26,10014552/Chicago,10014552,Chicago,8/30/2015,4,129.440002,432884006,USD,74882
27,10014552/Chicago,10014552,Chicago,9/1/2015,2,129.440002,433581006,USD,16695
28,10014552/Chicago,10014552,Chicago,10/25/2015,4,132.290009,448117006,USD,95543
29,10014552/Chicago,10014552,Chicago,10/28/2015,4,139.449997,448776006,USD,17060
...,...,...,...,...,...,...,...,...,...
119630,9952426/New-York,9952426,New-York,2/28/2016,2,189.510010,HD-156758,USD,58060
119631,9952426/New-York,9952426,New-York,2/28/2016,2,189.510010,HD-156757,USD,74952
119632,9952426/New-York,9952426,New-York,3/7/2016,2,189.510010,SC-459870477,USD,45795
119633,9952426/New-York,9952426,New-York,3/10/2016,2,189.510010,HD-157989,USD,84156
119634,9952426/New-York,9952426,New-York,5/12/2016,2,68.400002,SC-464704001,USD,28698
119635,9952426/New-York,9952426,New-York,5/21/2016,2,284.269989,HD-163365,USD,5118
119636,9952426/New-York,9952426,New-York,5/25/2016,2,189.510010,HD-163669,USD,3398
119637,9952426/New-York,9952426,New-York,5/27/2016,2,191.570007,HD-163851,USD,51294
119638,9952426/New-York,9952426,New-York,6/3/2016,2,189.510010,100001288,USD,77256
119639,9952426/New-York,9952426,New-York,6/4/2016,2,81.349998,HD-164465,USD,9393
119640,9952426/New-York,9952426,New-York,6/8/2016,2,191.710007,100001331,USD,20280
119641,9952426/New-York,9952426,New-York,6/10/2016,2,81.349998,HD-164915,USD,68926
119642,9952426/New-York,9952426,New-York,6/22/2016,2,176.559998,SC-467448700,USD,36497
119643,9952426/New-York,9952426,New-York,6/29/2016,2,176.559998,SC-467903015,USD,57789
119644,9952426/New-York,9952426,New-York,7/2/2016,2,81.349998,HD-166920,USD,55708
119645,9952426/New-York,9952426,New-York,7/5/2016,2,81.349998,HD-167121,USD,75377
119646,9952426/New-York,9952426,New-York,7/5/2016,2,81.349998,HD-167090,USD,12886
119647,9952426/New-York,9952426,New-York,7/5/2016,2,189.510010,HD-167186,USD,14323
119648,9952426/New-York,9952426,New-York,7/11/2016,2,81.349998,SC-468635401,USD,31862
119649,9952426/New-York,9952426,New-York,7/11/2016,2,68.400002,SC-468627933,USD,82063
119650,9952426/New-York,9952426,New-York,7/20/2016,2,189.510010,HD-168635,USD,69570
119651,9952426/New-York,9952426,New-York,7/30/2016,2,189.510010,HD-169586,USD,71811
119652,9952426/New-York,9952426,New-York,8/1/2016,2,68.400002,SC-470084055,USD,67100
119653,9952426/New-York,9952426,New-York,8/7/2016,2,189.510010,HD-170425,USD,69827
119654,9952426/New-York,9952426,New-York,8/15/2016,2,189.510010,HD-171286,USD,70801
119655,9952426/New-York,9952426,New-York,8/16/2016,2,81.349998,HD-171401,USD,92811
119656,9952426/New-York,9952426,New-York,9/9/2016,2,68.400002,SC-472670440,USD,28745
119657,9952426/New-York,9952426,New-York,9/13/2016,2,81.349998,HD-174116,USD,71380
119658,9952426/New-York,9952426,New-York,9/18/2016,2,81.349998,HD-174633,USD,19839
119659,9952426/New-York,9952426,New-York,9/20/2016,2,68.400002,SC-475391720,USD,98212

In [4]:
# Average daily usage sorted on the basis of Reference of the product.
#def avg_usage():
avg_daily_usage = lokad_orders.groupby('Ref')['Quantity'].mean().astype(int)
    #return avg_daily_usage
avg_daily_usage.to_csv('Quantity.csv')

In [5]:
# Reading thr reference id and Daily usage of the product from the Quantity.csv

colnames = ['Ref', 'DailyUsage']
data = pd.read_csv('Quantity.csv', names = colnames, header = None)

data

          Ref  DailyUsage
0     9952426           2
1    10014552           2
2    10095232           2
3    10099950           2
4    10132892           2
5    10136626           2
6    10210677           2
7    10255812           6
8    10422793           2
9    10592438           2
10   10595489           2
11   10678449           2
12   10764226           2
13   11045096           2
14   11097836           2
15   11481389           2
16   11557472           2
17   11635178           2
18   11711100           2
19   11711150           2
20   11711636           2
21   11780124           2
22   11788268           3
23   11800905           2
24   11906239           2
25   11914966           2
26   11929369           2
27   11941800           2
28   12401265           2
29   12407652           2
..        ...         ...
76   14820865           2
77   14895172           2
78   14901389           2
79   14993287           2
80   15034737           2
81   15063964           2
82   15092233           2
83   15149291           2
84   15343952           2
85   15410849           2
86   15416092           2
87   15431986           2
88   15519926           2
89   15586718           2
90   15641711           2
91   15808622           2
92   15880950           2
93   15963625           2
94   16018733           2
95   16075571           2
96   16089695           2
97   16187687           2
98   16188573           2
99   16239251           2
100  16277400           2
101  16363786           2
102  16401974           2
103  16412231           2
104  16430058           4
105  16595101           2

[106 rows x 2 columns]

In [6]:
new_data = new_purchase_data.merge(data, on = 'Ref', right_index = True)
new_data.to_csv('temp1.csv')

### Lead Demand calculation 
#### The projected level of demand for a product from consumers during its lead time from the supplier to the retailer
#### Lead Demand = Lead Time(LT in days) * Avg Daily Usage(of products in units)

In [7]:
new_data['Demand'] = new_data.LeadTime * new_data.DailyUsage
new_data['Demand']

0         126
1           6
2         628
3       11006
4       11006
5         126
6           6
7       11428
8         144
9         386
10        162
11        158
12      11428
13        242
14        614
15      11392
16         30
17         64
18        294
19         78
20        102
21      11392
22         64
23         34
24        258
25      11482
26      11554
27         78
28        102
29      11482
        ...
1046      124
1047      126
1048      112
1049       88
1050      432
1051      112
1052      118
1053      114
1054      116
1055       58
1056      106
1057      264
1058      286
1059      580
1060      702
1061    11470
1062      264
1063    11472
1064      100
1065      140
1066      122
1067      130
1068      114
1069      264
1070    11156
1071    11540
1072      624
1073      164
1074      124
1075    11542
Name: Demand, Length: 1076, dtype: int64

In [8]:
Avg_demand = new_data.groupby('Ref')['Demand'].mean()
Avg_demand

Ref
9952426      116.000000
10014552    2842.222222
10095232     288.153846
10099950    4426.750000
10132892    1339.200000
10136626    1770.000000
10210677    2098.333333
10255812    5318.571429
10422793     171.200000
10592438    1566.500000
10595489    1340.000000
10678449    3976.666667
10764226     138.222222
11045096    4671.400000
11097836    1892.285714
11481389    2400.000000
11557472     300.500000
11635178     116.000000
11711100    3963.111111
11711636    2266.000000
11780124    4888.571429
11788268    3147.500000
11800905     184.666667
11906239    2099.000000
11914966    1258.400000
11929369    4230.000000
11941800    2266.000000
12401265     321.000000
12409642    3937.333333
12451991    2318.545455
               ...
14789055    1959.692308
14820865     184.750000
14895172     229.000000
14901389      65.000000
15034737    2651.333333
15063964    1790.500000
15092233    1985.076923
15149291    1738.000000
15343952    3830.888889
15410849    3493.500000
15416092    4206.363636
15431986    3315.272727
15519926    2987.238095
15586718    5809.000000
15641711    4554.400000
15808622    1404.555556
15880950    2805.000000
15963625    4897.600000
16018733    2394.933333
16075571    1772.857143
16089695    1566.500000
16187687    4327.500000
16188573    2449.000000
16239251    3086.000000
16277400    2318.545455
16363786    2904.000000
16401974    1866.142857
16412231    2435.333333
16430058    4008.000000
16595101    2043.000000
Name: Demand, Length: 100, dtype: float64

In [16]:
Avg_demand.to_csv('temp_Davg.csv')

colnames = ['Ref','Davg']

new_df = pd.read_csv('temp_Davg.csv', names = colnames, header = None)

new_df

         Ref         Davg
0    9952426   116.000000
1   10014552  2842.222222
2   10095232   288.153846
3   10099950  4426.750000
4   10132892  1339.200000
5   10136626  1770.000000
6   10210677  2098.333333
7   10255812  5318.571429
8   10422793   171.200000
9   10592438  1566.500000
10  10595489  1340.000000
11  10678449  3976.666667
12  10764226   138.222222
13  11045096  4671.400000
14  11097836  1892.285714
15  11481389  2400.000000
16  11557472   300.500000
17  11635178   116.000000
18  11711100  3963.111111
19  11711636  2266.000000
20  11780124  4888.571429
21  11788268  3147.500000
22  11800905   184.666667
23  11906239  2099.000000
24  11914966  1258.400000
25  11929369  4230.000000
26  11941800  2266.000000
27  12401265   321.000000
28  12409642  3937.333333
29  12451991  2318.545455
..       ...          ...
70  14789055  1959.692308
71  14820865   184.750000
72  14895172   229.000000
73  14901389    65.000000
74  15034737  2651.333333
75  15063964  1790.500000
76  15092233  1985.076923
77  15149291  1738.000000
78  15343952  3830.888889
79  15410849  3493.500000
80  15416092  4206.363636
81  15431986  3315.272727
82  15519926  2987.238095
83  15586718  5809.000000
84  15641711  4554.400000
85  15808622  1404.555556
86  15880950  2805.000000
87  15963625  4897.600000
88  16018733  2394.933333
89  16075571  1772.857143
90  16089695  1566.500000
91  16187687  4327.500000
92  16188573  2449.000000
93  16239251  3086.000000
94  16277400  2318.545455
95  16363786  2904.000000
96  16401974  1866.142857
97  16412231  2435.333333
98  16430058  4008.000000
99  16595101  2043.000000

[100 rows x 2 columns]

### Variance of Demand

In [10]:
var_LD = new_data.groupby('Ref')['Demand'].var()

In [11]:
var_LD.fillna(0).astype(int)

Ref
9952426          5408
10014552     24108017
10095232       109704
10099950     32517372
10132892     12864465
10136626     18551552
10210677     20790738
10255812    163252318
10422793        43029
10592438     15062667
10595489     11303059
10678449     30266538
10764226        20454
11045096     34209854
11097836     16010086
11481389     23971425
11557472        57319
11635178            0
11711100     31448475
11711636     19514166
11780124     33300036
11788268     46779161
11800905        21227
11906239     18679391
11914966     10743782
11929369     38858452
11941800     19514166
12401265       200978
12409642     30043405
12451991     20649174
              ...
14789055     17042844
14820865        18938
14895172        34604
14901389         6962
15034737     24211028
15063964     15647159
15092233     17212146
15149291     15833189
15343952     30369864
15410849     27203169
15416092     32684322
15431986     26861677
15519926     23469346
15586718     36130162
15641711     34740392
15808622     13419949
15880950     22839897
15963625     36033538
16018733     21021299
16075571     18139146
16089695     15062667
16187687     29433509
16188573     22764289
16239251     27318054
16277400     20649174
16363786     24951364
16401974     16646641
16412231     21844168
16430058     85272755
16595101     18825859
Name: Demand, Length: 100, dtype: int32

## Standard deviation of demand

In [12]:
# The standard deviation is calculated for it's usage in the safety stock level calculation.

In [13]:
sigma_LD = new_data.groupby('Ref')['Demand'].std().fillna(0).astype(int)
sigma_LD.to_csv('temp.csv')
colname = ['Ref', 'sigmaD']
df = pd.read_csv('temp.csv', names = colname, header = None)
df

         Ref  sigmaD
0    9952426      73
1   10014552    4909
2   10095232     331
3   10099950    5702
4   10132892    3586
5   10136626    4307
6   10210677    4559
7   10255812   12777
8   10422793     207
9   10592438    3881
10  10595489    3362
11  10678449    5501
12  10764226     143
13  11045096    5848
14  11097836    4001
15  11481389    4896
16  11557472     239
17  11635178       0
18  11711100    5607
19  11711636    4417
20  11780124    5770
21  11788268    6839
22  11800905     145
23  11906239    4321
24  11914966    3277
25  11929369    6233
26  11941800    4417
27  12401265     448
28  12409642    5481
29  12451991    4544
..       ...     ...
70  14789055    4128
71  14820865     137
72  14895172     186
73  14901389      83
74  15034737    4920
75  15063964    3955
76  15092233    4148
77  15149291    3979
78  15343952    5510
79  15410849    5215
80  15416092    5717
81  15431986    5182
82  15519926    4844
83  15586718    6010
84  15641711    5894
85  15808622    3663
86  15880950    4779
87  15963625    6002
88  16018733    4584
89  16075571    4259
90  16089695    3881
91  16187687    5425
92  16188573    4771
93  16239251    5226
94  16277400    4544
95  16363786    4995
96  16401974    4080
97  16412231    4673
98  16430058    9234
99  16595101    4338

[100 rows x 2 columns]

In [14]:
new_purchase_data.merge(df, on = 'Ref', right_index = True).to_csv('temp1.csv')

### Lead Demand Forecast

In [15]:
# Decision Tree Algorithm

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# define the dataset